### ISSUE TITLE
FCS clean-genome (bg)zip support

### ISSUE THREAD

**Issue by fgvieira** [ncbi/fcs-gx#5]
As far as I could see, `gx clean-genome` does not support gzip'ed files. Would it be possible to add `gzip` input and output support?
It would be great if the output was `bgzip`'ed, as the two formats are compatible but `bgzip` allows for random access.

**Comment by etvedte** [comment]
Hello,

We have added a work ticket to discuss implementing this for our next release. Our latest release v0.5.4 was in late June, so I don't expect this to happen for another few months.

Eric

**Comment by etvedte** [comment]
Hello,

gx clean-genome does support compressed input/output files. When input is specified as `--input=/path/to/input.XX`, it is decompressed automatically based on `.XX` extension (requires the corresponding compression tool to be installed)

gx produces the cleaned output to stdout, meaning you can use your preferred compression method to handle the output.

`gx clean-genome --input=genome.fa.gz --action-report=fcs_gx_report.txt | -gzip -c > cleaned.fa.gz `
